# Generated by Django 6.0.5 on 2026-05-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loancollateral_loanguarantor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('min_amount',),
            },
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loan',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loancollateral',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
