# Generated by Django 6.0.5 on 2026-05-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanratetier_alter_loan_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='repayment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='requested_disbursement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
