# Generated by Django 6.0.5 on 2026-05-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
